[project]
name = "scc-carla"
version = "0.1.0"
description = "SCC@CARLA Cluster Management CLI"
readme = "README.md"
authors = [
    { name = "Isaac David", email = "orpheezt@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ansible-core>=2.21.4",
    "platformdirs>=4.11.11",
    "pydantic-settings>=2.15.0",
    "pyturso>=0.7.2",
    "rich>=15.0.0",
    "typer>=0.27.2",
    "scc-core",
    "scc-provider-libvirt",
    "scc-provider-helvetios",
]

[project.optional-dependencies]
libvirt = [
    "scc-provider-libvirt",
]
helvetios = [
    "scc-provider-helvetios",
]
all = [
    "scc-provider-libvirt",
    "scc-provider-helvetios",
]

[project.scripts]
scc = "scc_carla:app"
scc-carla = "scc_carla:app"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "packages/*",
]

[tool.uv.sources]
scc-core = { workspace = true }
scc-provider-libvirt = { workspace = true }
scc-provider-helvetios = { workspace = true }

[dependency-groups]
dev = [
    "ruff>=0.16.8",
    "ty>=0.0.81",
]
