from enum import StrEnum


class LifecyclePhase(StrEnum):
    DEFINED = "DEFINED"
    PROVISIONING = "PROVISIONING"
    INSTALLING = "INSTALLING"
    BOOTING = "BOOTING"
    CONFIGURING = "CONFIGURING"
    ACTIVE = "ACTIVE"
    DECOMMISSIONING = "DECOMMISSIONING"
    OFFLINE = "OFFLINE"
    ERROR = "ERROR"
